env:
  - "ACTIVERECORD_VERSION=4.2"
  - "ACTIVERECORD_VERSION=4.1"
  - "ACTIVERECORD_VERSION=4.0"
  - "ACTIVERECORD_VERSION=master"

rvm:
  - 2.0.0
  - 2.1.2
  - 2.2.0
  - ruby-head
  - jruby-19mode
  - rbx

